name: Quality Assurance

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  quality-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Install ShellCheck
      run: sudo apt-get update && sudo apt-get install -y shellcheck
      
    - name: Make scripts executable
      run: chmod +x sync_script.sh test-quality.sh
      
    - name: ShellCheck Analysis
      run: shellcheck --format=gcc sync_script.sh test-quality.sh
      
    - name: Secret Scanning with TruffleHog
      uses: trufflesecurity/trufflehog@main
      with:
        path: ./
        extra_args: --debug --only-verified
        
    - name: Security Analysis with Semgrep
      uses: returntocorp/semgrep-action@v1
      with:
        config: >-
          p/security-audit
          p/secrets
          p/bash
        
    - name: CodeQL Analysis
      uses: github/codeql-action/init@v3
      with:
        languages: javascript
        
    - name: Basic Functionality Tests
      run: ./test-quality.sh
